saz/puppet-sudo

files/sudoers.rhel7
manifests/params.pp

Modified params.pp to add case for RedHat EL7 and captured the default /etc/sudoers from EL7.
I left the default for RedHat still set to EL6 as I think its the more common install right now.

Add case in RedHat section for EL7

---

manifests/conf.pp
spec/defines/sudo_spec.rb

Currently, the module does a visudo -c - which check everyfile - to
validate that the sudo::conf was correct. Unfortunately, if one needs
to be in purge -> false, and some files there have wrong permissions
because of a packaging related issues, it cancels the sudo::conf even
if the rule is perfectly valid. This patch aims to fix that, using the
-f option of visudo to validate only the file we are adding.

conf: Fix the scope of the visudo -c check

---

files/sudoers.openbsd
lib/facter/sudoversion.rb
manifests/package.pp
manifests/params.pp

Patch below adds support for OpenBSD.
The sudoers file is taken from a -current OpenBSD system, with just the added 
#includedir /etc/sudoers.d 
statement.
Further changes to params.pp for OpenBSD support, mostly copied from freebsd.
The little change to package.pp was necessary, because sudo is part of the base installation, therefore no package needed to be installed.

OpenBSD compatibility.

---

manifests/configs.pp

Added configs_hash variable to allow passing a configuration hash to sudo::configs. I use it to store the configuration inside Foreman.

Added configs_hash variable

---

lib/facter/sudoversion.rb

By my reading of the rpm manual page, these options are not meaningful
in query mode. (I could be wrong, of course, in which case this PR should be 
discarded.) For AIX users with very old versions of RPM, adding these
options to the command line causes error output to be mailed with every
run of the refresh-mcollective-metadata cron job.

Remove --nosignature and --nodigest

---

manifests/params.pp
spec/classes/sudo_spec.rb

Hi,
I checked the download site http://www.sudo.ws/sudo/dist/packages/Solaris/10/
With this patch we will download the right package for the right maschine.
NOTE: This patch is untested, because i use OpenCSW Sudo http://www.opencsw.org/packages/CSWsudo/
If i should make a patch for use OpenCSW, let me know.

Use hardwareisa in download URL

---

.fixtures.yml

Not every version of git can handle GitHub's http->https redirects when cloning.

Adjust stdlib fixture url

---

files/sudoers.rhel6
files/sudoers.rhel7

Without this patch you cannot run Puppet Enterprise without pathing (sudo /usr/local/bin/puppet) but also have issues with r10k as it looks in $PATH for the puppet binary. This removes the need to `sudo su -` just to run r10k.

Bring RHEL secure_path settings in line with other OSes, supports PE binary location

---

files/sudoers.darwin
manifests/init.pp
manifests/package.pp
manifests/params.pp

This adds support for OSX. The `sudoers.darwin` file is what comes default on Yosemite (what I used to test) with an `#includedir` directive added for this module to work.

Add support for OSX

---

metadata.json

Clicking the link "Project URL" on https://forge.puppetlabs.com/saz/sudo send users to https://forge.puppetlabs.com/examplecorp/mymodule, which is a faulty URL.

Fix URL to project_page

---

manifests/params.pp

Kali is a Debian derivative. Facter reports:
```
operatingsystem => Debian
operatingsystemmajrelease => Kali Linux 1
operatingsystemrelease => Kali Linux 1.1.0
os => {"name"=>"Debian", "family"=>"Debian", "release"=>{"major"=>"Kali Linux 1", "minor"=>"1", "full"=>"Kali Linux 1.1.0"}, "lsb"=>{"distcodename"=>"moto", "distid"=>"Kali", "distdescription"=>"Kali GNU/Linux 1.1.0", "distrelease"=>"1.1.0", "majdistrelease"=>"1", "minordistrelease"=>"1"}}
osfamily => Debian
```

Check for Kali Linux

---

manifests/conf.pp

Fixes https://github.com/saz/puppet-sudo/issues/143

Use class default not OS default for config_dir

---

manifests/package.pp

Using ensure_packages to take care of this so we don't run need
into conflicts state with different puppet module which also handle
sudo packages

Package resource gets conflict

---

README.md
manifests/init.pp
manifests/package.pp
manifests/params.pp

This pull will enable support for ldap package.
special case: gentoo. support for puppet portage module is needed.
an additional variable has been added, $package_ldap.

Add LDAP support to the package

---

manifests/params.pp

Param is set to "undef", so ldap is not supported but module can be
compiled.

Fix missing param package_ldap for Solaris and AIX OS.

---

templates/sudoers.erb

The new AIO binary location is not part of `secure_path` right now. That means I can't `sudo puppet`, I have to `sudo /opt/puppetlabs/bin/puppet` and that's just awkward. Nothing else should be in `/opt/puppetlabs/bin` so this feels like a good solution to me.

Add Puppet AIO binary path to secure_path

---

manifests/params.pp

Current comparison method don't work on puppet 2.7 with ruby 1.8.x and using versioncmp
is more elegant.
Change-Id: I5b2f869c49ce964a366773339c42934a30ac09e2

Use versioncmp function to compare Debian vers in param class.

---

files/sudoers.aix
files/sudoers.archlinux
files/sudoers.darwin
files/sudoers.debian
files/sudoers.freebsd
files/sudoers.gentoo
files/sudoers.olddebian
files/sudoers.omnios
files/sudoers.openbsd
files/sudoers.rhel5
files/sudoers.rhel6
files/sudoers.rhel7
files/sudoers.smartos
files/sudoers.solaris
files/sudoers.suse
files/sudoers.ubuntu
manifests/conf.pp
spec/defines/sudo_spec.rb

The sudoers files for rhel5 and rhel6 do not reflect that they are managed by Puppet.  Add consistent comment lines at the top of all the sudoers flatfiles.

Add file managed by Puppet comments to all sudoers files

---

files/sudoers.rhel5
files/sudoers.rhel6
files/sudoers.rhel7

sudo: It was discovered that the default sudo configuration on Red Hat Enterprise Linux and possibly other Linux implementations preserves the value of **INPUTRC** which could lead to information disclosure. A local user with sudo access to a restricted program that uses readline could use this flaw to read content from specially formatted files with elevated privileges provided by `sudo`.

fix for CVE-2016-7091 by removing INPUTRC

---

.travis.yml
Gemfile
README.md
manifests/conf.pp

When using hiera, templates are not correctly parsed.
Changed syntax in order to support template from hiera.
README has been changed according to.
Also, the supported OS are now written in README, as a lot are supported but not written.

Ruby travis fixed, template through hiera fixed and README improved

---

manifests/init.pp
manifests/package.pp
manifests/params.pp
spec/classes/package_spec.rb

but enhance the default case, to allow installation of
package also on OpenBSD.
reason for that is that OpenBSD recently dropped sudo from base
and moved it to ports/packages.
At some point in time, a default in param.pp could be added.
I tried with versioncmp on operationgsystemrelease, but I only
have 5.7-snapshots, or 5.8-beta hosts around, that versioncmp
messed totally up with those in order to get it right :(
while there, I added/enhanced spec tests for OpenBSD package
installation.

remove the empty case for OpenBSD in package.pp installation,

---

templates/users_groups.erb

We have pre-receive hooks that check erb syntax, and the % for sudo groups breaks that parser. %% escapes it

escape % in users_groups for erb syntax check

---

.rubocop.yml

While submitting PR #178, I noticed Travis reporting a number of rubocop offenses. This should fix them.
- Lint/Eval has been renamed Security/Eval
- Style/MethodCallParentheses has been renamed MethodCallWithoutArgsParentheses
- new cop Metrics/BlockLength has a default of 25 lines, which is too short for the inline manifests.

Fix three rubocop offences

---

manifests/init.pp

The anchor is creating a dependency cycle described in issue https://github.com/saz/puppet-sudo/issues/202

replace anchor with contain

---

manifests/conf.pp
manifests/init.pp
spec/defines/sudo_spec.rb

Change the way visudo checks are done with 2 options.
The 2 options are $delete_on_error and $validate_single.
If $delete_on_error is true the configuration is deleted if visudo -c return
an error. If false the error will be only notified but the file will not be
deleted. Default is true
if $validate_single is true the file resource will run with validate_cmd to
test the single files and if there's an error the old file will not be
substituted or deleted. Default is false
Will help with #184 and #125

Changed the file resource in conf.pp to use validate_cmd by default

---

manifests/init.pp

With the introduction of Puppet 4 data types in a recent commit to this module the accepted types for the $purge_ignore parameter got limited to strings only. The Puppet file resource however accepts arrays for its $ignore parameter as well. So the following examples should both be valid:
```
class { 'sudo':
purge_ignore => 'custom_*',
}
```
```
class { 'sudo':
purge_ignore => ['custom_*', 'vagrant'],
}
```
Currently the second declaration fails. This commit fixes that.

Let $purge_ignore accept an array of strings

---

manifests/init.pp

so we probably dont want to try to ensure it when undef (this is breaking on OSX)

Currently we set package to undef for a couple of OSs

---

manifests/params.pp

This anchors the regex so that RHEL 5.10 and 5.11 don't get caught.

anchors rhel 5 regex in params.pp

---

Rakefile
manifests/conf.pp
manifests/init.pp
manifests/package.pp

Absolute classname inclusion was a problem before Puppet 4. With Puppet
4 this got fixed and the current best practice is to not use absolute
classnames anymore.
This commit configures the puppet-lint-absolute_classname-check plugin
to reverse its checking.
Fixes #235.

Reverse absolute classname linter

---

.rubocop.yml
manifests/params.pp

Manjarolinux is a derivative of Archlinux ( and an Archlinux family member).
An alternative to my solution would be to move the Archlinux section up from "operatingsystem" section to "osfamily" section. If you would prefer that solution, I'll be happy to implement in that fashion.

support manjaro linux

---

.rubocop.yml

Various rename of rubocop configurations:
```
.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
Error: The `Layout/AlignArray` cop has been renamed to `Layout/ArrayAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/AlignHash` cop has been renamed to `Layout/HashAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/AlignParameters` cop has been renamed to `Layout/ParameterAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/IndentFirstArrayElement` cop has been renamed to `Layout/FirstArrayElementIndentation`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/IndentFirstHashElement` cop has been renamed to …
```

Rename some rubocop rules

---

README.md
manifests/conf.pp
manifests/init.pp
spec/acceptance/sudo_conf_spec.rb
spec/defines/sudo_spec.rb

If optional parameter `suffix` is specified then the specified
suffix will be added to each file entry in the `/etc/sudoers.d`
directory.
The motivation here is to allow a configuration.
```puppet
class{'sudo':
suffix => '_puppet',
ignore => '*[!_puppet]',
}
sudo::conf{'admins':
content => '...',
}
```
this will allow puppet to only purge the files that it created.
In particular sudo file entries which are dropped in via an RPM
will not be clobbered by the module. However puppet created
files will still be purged.

New parameter suffix to main class

---

.fixtures.yml
manifests/params.pp
spec/classes/sudo_spec.rb

the two variables `$package_source ` and `$package_admin_file` were
declared multiple times. This triggers a compilation error. Observed in
https://github.com/voxpupuli/puppet-prometheus/pull/574

fix duplicate variable declaration

---

manifests/init.pp
manifests/params.pp
spec/classes/sudo_spec.rb
templates/sudoers.aix.erb
templates/sudoers.archlinux.erb
templates/sudoers.darwin.erb
templates/sudoers.freebsd.erb
templates/sudoers.gentoo.erb
templates/sudoers.olddebian.erb
templates/sudoers.omnios.erb
templates/sudoers.openbsd.erb
templates/sudoers.rhel5.erb
templates/sudoers.rhel6.erb
templates/sudoers.rhel7.erb
templates/sudoers.rhel8.erb
templates/sudoers.smartos.erb
templates/sudoers.solaris.erb
templates/sudoers.suse.erb

Reverts previous behavior of enabling the wheel group (with password) on RHEL 7 and 8 inline with the default configuration from Redhat.
Retains behavior for all other OS's but restores the comments and example config from the default config files.
Essentially this keeps the functionality of the new wheel_config parameter provided by 80a5be316f0606599ed7ac06c656a72b543d5ae3 but restores the original behavior of the module when this parameter isn't used.
Fixes #276

Restore format and behavior prior to adding wheel_config parameter

---

README.md
manifests/conf.pp
manifests/init.pp
spec/acceptance/sudo_conf_spec.rb
spec/defines/sudo_spec.rb

A previous attempt in
https://github.com/saz/puppet-sudo/pull/248
to allow only files created with the suffix `_puppet` to be
purged is faulty. In particular with
```
class{'sudo':
suffix              => '_puppet',
purge_ignore => '*[!_puppet]',
}
```
Does not work as files names shorter than the length of string `_puppet` are
not ignored and so are deleted.
Switching to prefix
```
class{'sudo':
prefix             => 'puppet_',
purge_ignore => '[!puppet_]*',
}
```
Gives the desired result.
```txt
irb(main):001:0> Dir.glob('[!puppet_]*')
=> ["short", "longfilename"]
So the files `short` and `longfilename` will be ignored correctly.

Add prefix parameter to prefix all sudoers.d entries

---

README.md

drop purge_ignore example, as it is not working as documented

---

README.md

E.g. `includedirsudoers` has been removed a long time ago but was still mentioned within the README.
This PR will just mention REFERENCE.md, which is automatically generated.

Remove parameters from README.md, mention REFERENCE.md, fixes #197

---

lib/puppet/functions/sudo/defaults.rb

in puppet undef seems to be different to nil and you need to test for both. See
https://github.com/puppetlabs/puppetlabs-stdlib/blob/5f3d86ccadf020522d69c31b3ded9e6739276fba/lib/puppet/parser/functions/delete_undef_values.rb#L35 for example

Fix defaults functions for key-only configs

---

templates/sudoers.aix.erb
templates/sudoers.archlinux.erb
templates/sudoers.darwin.erb
templates/sudoers.debian.erb
templates/sudoers.freebsd.erb
templates/sudoers.gentoo.erb
templates/sudoers.omnios.erb
templates/sudoers.openbsd.erb
templates/sudoers.rhel.erb
templates/sudoers.smartos.erb
templates/sudoers.solaris.erb
templates/sudoers.suse.erb
templates/sudoers.ubuntu.erb

Revert "Include defaults as last line on all platforms"
